### ISSUE TITLE
Change background colour to white 

### ISSUE THREAD

**Issue by CaiCardenas** [MarcoSero/HackerNews#10]
Just noticed it's an off-white?

**Comment by MarcoSero** [comment]
Looks white to me?

<img width="372" alt="screen shot 2015-07-25 at 09 20 54" src="https://cloud.githubusercontent.com/assets/867996/8888656/908ecf12-32ae-11e5-941a-0d7ebca6315e.png">

Reopen if I'm wrong.

**Comment by CaiCardenas** [comment]
Ah sorry, I think it was an optical illusion with one of the favicons! My bad
