### ISSUE TITLE
Remove white circle background from loading animation

### ISSUE THREAD

**Issue by CaiCardenas** [MarcoSero/HackerNews#11]
Because you are removing the previous content while the new content loads in (when switching menu items), we don't need the white circle background, and can keep the content background as white (not off-white).

However, if you go for using the same loading animation for loading in new stories and loading comments (which I think will work well), you'll need to reintroduce this usage of the white circular background and white overlay over the content. I'm probably not explaining this very well so just ask :)

**Comment by MarcoSero** [comment]
Ok I see why you want to remove the white circle. But would you like to use that to load comments instead?
Right now for loading comments we use a smaller loading indicator which is shown just below the title.

**Comment by CaiCardenas** [comment]
Yeah, when loading and you can still see the previous content underneath (comments section and loading in paginated stories), include the white circle background with a black opacity overlay. When the content is hidden (switching between story categories) omit the white circle background and remove black overlay (background is just white).

**Comment by MarcoSero** [comment]
Yeah it looks better without the black opacity overlay if there's no content. I've removed it.

For loading comments and the next page in stories though, I prefer the smaller indicator because it leaves the app responsive, so that the user can do other things while the page or comments are loading.

**Comment by CaiCardenas** [comment]
Yeah that makes sense. Is it then possible to at least give the loading icon some more space? At the moment it feels too squashed in at the bottom.

**Comment by MarcoSero** [comment]
I have increased the inset from 5pt to 16pt.
