### ISSUE TITLE
Jobs section doesn't load favicons

### ISSUE THREAD

**Issue by CaiCardenas** [MarcoSero/HackerNews#14]

**Comment by MarcoSero** [comment]
Jobs are always posted directly on Hacker News so they lack a domain.

**Comment by CaiCardenas** [comment]
I'm seeing domains. And weirdly now the favicons are loading!

**Comment by MarcoSero** [comment]
Ah yeah my bad, I got confused with "Ask HN". For loading favicons I'm using an external service. It might be that it was down for a bit.
